# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-case-conflict
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: pretty-format-json
      args:
        - --autofix
    - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.8
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]

- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
  - id: black
    types: [python]

- repo: https://github.com/google/yamlfmt
  rev: v0.13.0
  hooks:
    - id: yamlfmt

- repo: https://github.com/rhysd/actionlint
  rev: v1.7.3
  hooks:
    - id: actionlint

{% if cookiecutter.html != 'No' %}
- repo: https://github.com/Riverside-Healthcare/djLint/
  rev: v1.35.2
  hooks:
    - id: djlint-reformat-django

- repo: https://github.com/adamchainz/djade-pre-commit
  rev: 1.1.1
  hooks:
    - id: djade
      args: [--target-version, "5.1"]
{% endif %}
