[tool.poetry]
name = "{{ cookiecutter.project_slug }}"
version = "0.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.12"
dj-database-url = "2.2.0"
django = "5.0.6"
django-extensions = "3.2.3"
{%- if cookiecutter.html == 'HTMX' %}
django-htmx = "1.17.2"
{%- endif %}
{%- if cookiecutter.api != 'No' %}
django-ninja = "1.2.0"
{%- endif %}
{%- if cookiecutter.api == 'Django Ninja CRUD' %}
django-ninja-crud = "0.2.0"
{%- endif %}
gunicorn = "22.0.0"
{%- if cookiecutter.database == 'PostgreSQL' %}
psycopg2-binary = "2.9.9"
{%- endif %}
python-decouple = "3.8"
{%- if cookiecutter.use_sentry %}
sentry-sdk = {extras = ["django"], version = "2.7.1"}
{%- endif %}
{%- if cookiecutter.staticfiles %}
whitenoise = {extras = ["brotli"], version = "6.7.0"}
{%- endif %}

[tool.poetry.group.dev.dependencies]
model-bakery = "1.18.2"
pre-commit = "3.7.1"
pytest = "8.2.2"
pytest-django = "4.8.0"
pytest-mock = "3.14.0"

{% if cookiecutter.html != "No" %}
[tool.djlint]
blank_line_after_tag="endblock,extends"
blank_line_before_tag="block"
{% endif %}

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "{{ cookiecutter.project_slug }}.settings"
python_files = "tests.py test_*.py *_tests.py"


[tool.ruff]
select = ["E", "F", "I", "S", "TRY"]
ignore = ["E501"]
line-length = 88

[tool.ruff.per-file-ignores]
"manage.py" = ["TRY003"]
"**/tests/**" = ["S101"]
