name: Python application
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: pipx install poetry
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'poetry'
      - run: make install
      - run: make lint
      - run: make test
