name: Sync Dependencies
on:
  pull_request:
    paths:
      - 'pyproject.toml'
      - 'poetry.lock'
      - '{{cookiecutter.project_slug}}/pyproject.toml'
      - '{{cookiecutter.project_slug}}/poetry.lock'
jobs:
  sync-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Sync template dependencies
        run: |
          # Extract dependencies from root pyproject.toml template group
          python3 -c '
          import toml
          import json

          # Read root pyproject.toml
          with open("pyproject.toml") as f:
              root_data = toml.load(f)

          # Read template pyproject.toml
          with open("{{cookiecutter.project_slug}}/pyproject.toml") as f:
              template_data = toml.load(f)

          # Get template dependencies
          template_deps = root_data["tool"]["poetry"]["group"]["template"]["dependencies"]

          # Update template dependencies
          template_data["tool"]["poetry"]["dependencies"].update(template_deps)

          # Write back to template pyproject.toml
          with open("{{cookiecutter.project_slug}}/pyproject.toml", "w") as f:
              toml.dump(template_data, f)
          '

          # Update lock file
          cd {{cookiecutter.project_slug}}
          poetry lock --no-update
