name: Trigger Child Projects

"on":
  release:
    types: [published]

jobs:
  trigger-child-projects:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger child projects to update with cruft
        run: |
          # Get the list of child repositories from environment variable
          # Each repository should be in the format "owner/repo"
          if [ -n "${{ vars.CHILD_REPOSITORIES }}" ]; then
            IFS=',' read -ra REPOS <<< "${{ vars.CHILD_REPOSITORIES }}"
            for repo in "${REPOS[@]}"; do
              repo=$(echo "$repo" | xargs)  # Trim whitespace
              echo "Triggering repository: $repo"
              
              # Trigger repository_dispatch event
              curl -X POST \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Authorization: token ${{ secrets.CHILD_PROJECTS_TOKEN }}" \
                -H "User-Agent: django-template-release-trigger" \
                "https://api.github.com/repos/$repo/dispatches" \
                -d '{"event_type":"cruft_update","client_payload":{"template_version":"${{ github.event.release.tag_name }}","template_url":"${{ github.repository_url }}"}}'
              
              if [ $? -eq 0 ]; then
                echo "✅ Successfully triggered $repo"
              else
                echo "❌ Failed to trigger $repo"
              fi
            done
          else
            echo "No child repositories configured. Set CHILD_REPOSITORIES variable."
          fi